#!/usr/bin/env python
import subprocess
from os.path import abspath, dirname, join
from shutil import move
from argparse import ArgumentParser


def main():
    parser = ArgumentParser()
    parser.add_argument("--bzimage", type=str, help="Compressed kernel image", required=True)
    parser.add_argument("--output", type=str, help="Path to output vmlinux", required=True)
    parser.add_argument("--kallsyms", type=str, help="Path to System Map (kallsyms)", required=True)

    args = parser.parse_args()

    kdress_dir = dirname(abspath(__file__))
    tmp_filename = "/tmp/.vmlinux.abc"
    subprocess.call([join(kdress_dir, "kunpress"), args.bzimage, args.output])
    subprocess.call([join(kdress_dir, "build_ksyms"), args.output, tmp_filename, args.kallsyms])
    move(tmp_filename, args.output)


if __name__ == "__main__":
    main()
